<?php

namespace Northwestern\SysDev\DynamicForms;

use JWadhams\JsonLogic;
use Northwestern\SysDev\DynamicForms\JSONLogic\LodashFunctions\___;

class JSONLogicInitHelper
{
    /** This Lodash function is intentionally not offered. */
    private const NOT_IMPLEMENTED = 0;

    /** Implementation comes from northwestern-sysdev/lodash-php package */
    private const LIB_LODASH_PHP = 1;

    /**
     * The function is implemented by this package, in the {@see ___} class.
     */
    private const IN_PACKAGE = 3;

    public function __construct()
    {
        $this->registerLodash();
    }

    /**
     * Registers all the lodash functions.
     */
    private function registerLodash(): void
    {
        //This list contains all the lodash functions (supported by formsio) and implementation source
        // (0 is missing, self::LIB_LODASH_PHP is lodash-php library, self::LIB_MEIO is php-lodash library, and 3 is from this repo)
        $lodashList = [
            // Array
            ['chunk', self::LIB_LODASH_PHP],
            ['compact', self::LIB_LODASH_PHP],
            ['concat', self::LIB_LODASH_PHP],
            ['difference', self::LIB_LODASH_PHP],
            ['differenceBy', self::NOT_IMPLEMENTED],
            ['differenceWith', self::NOT_IMPLEMENTED],
            ['drop', self::LIB_LODASH_PHP],
            ['dropRight', self::LIB_LODASH_PHP],
            ['dropRightWhile', self::NOT_IMPLEMENTED],
            ['dropWhile', self::NOT_IMPLEMENTED],
            ['findIndex', self::LIB_LODASH_PHP],
            ['findLastIndex', self::LIB_LODASH_PHP],
            ['first', self::IN_PACKAGE],
            ['flatten', self::LIB_LODASH_PHP],
            ['flattenDeep', self::LIB_LODASH_PHP],
            ['flattenDepth', self::LIB_LODASH_PHP],
            ['fromPairs', self::IN_PACKAGE],
            ['head', self::LIB_LODASH_PHP],
            ['indexOf', self::LIB_LODASH_PHP],
            ['initial', self::LIB_LODASH_PHP],
            ['intersection', self::LIB_LODASH_PHP],
            ['intersectionBy', self::NOT_IMPLEMENTED],
            ['intersectionWith', self::NOT_IMPLEMENTED],
            ['join', self::IN_PACKAGE],
            ['last', self::LIB_LODASH_PHP],
            ['lastIndexOf', self::LIB_LODASH_PHP],
            ['nth', self::LIB_LODASH_PHP],
            ['slice', self::IN_PACKAGE],
            ['sortedIndex', self::IN_PACKAGE],
            ['sortedIndexBy', self::NOT_IMPLEMENTED],
            ['sortedIndexOf', self::IN_PACKAGE],
            ['sortedLastIndex', self::IN_PACKAGE],
            ['sortedLastIndexBy', self::NOT_IMPLEMENTED],
            ['sortedLastIndexOf', self::IN_PACKAGE],
            ['sortedUniq', self::IN_PACKAGE],
            ['sortedUniqBy', self::NOT_IMPLEMENTED],
            ['tail', self::LIB_LODASH_PHP],
            ['take', self::LIB_LODASH_PHP],
            ['takeRight', self::LIB_LODASH_PHP],
            ['takeRightWhile', self::LIB_LODASH_PHP],
            ['takeWhile', self::LIB_LODASH_PHP],
            ['union', self::LIB_LODASH_PHP],
            ['unionBy', self::NOT_IMPLEMENTED],
            ['unionWith', self::NOT_IMPLEMENTED],
            ['uniq', self::LIB_LODASH_PHP],
            ['uniqBy', self::NOT_IMPLEMENTED],
            ['uniqWith', self::NOT_IMPLEMENTED],
            ['unzip', self::LIB_LODASH_PHP],
            ['unzipWith', self::NOT_IMPLEMENTED],
            ['without', self::LIB_LODASH_PHP],
            ['xor', self::NOT_IMPLEMENTED],
            ['xorBy', self::NOT_IMPLEMENTED],
            ['xorWith', self::NOT_IMPLEMENTED],
            ['zip', self::LIB_LODASH_PHP],
            ['zipObject', self::LIB_LODASH_PHP],
            ['zipObjectDeep', self::LIB_LODASH_PHP],
            ['zipWith', self::NOT_IMPLEMENTED],
            // Collection
            ['countBy', self::NOT_IMPLEMENTED],
            ['every', self::LIB_LODASH_PHP],
            ['filter', self::LIB_LODASH_PHP],
            ['find', self::LIB_LODASH_PHP],
            ['findLast', self::LIB_LODASH_PHP],
            ['flatMap', self::NOT_IMPLEMENTED],
            ['flatMapDeep', self::NOT_IMPLEMENTED],
            ['flatMapDepth', self::NOT_IMPLEMENTED],
            ['groupBy', self::NOT_IMPLEMENTED],
            ['includes', self::IN_PACKAGE],
            ['invokeMap', self::NOT_IMPLEMENTED],
            ['keyBy', self::LIB_LODASH_PHP],
            ['map', self::LIB_LODASH_PHP],
            ['orderBy', self::IN_PACKAGE],
            ['partition', self::NOT_IMPLEMENTED],
            ['reduce', self::NOT_IMPLEMENTED],
            ['reduceRight', self::NOT_IMPLEMENTED],
            ['reject', self::LIB_LODASH_PHP],
            ['sample', self::LIB_LODASH_PHP], //untested
            ['sampleSize', self::LIB_LODASH_PHP], //untested
            ['shuffle', self::LIB_LODASH_PHP], //untested
            ['size', self::LIB_LODASH_PHP],
            ['some', self::LIB_LODASH_PHP],
            ['sortBy', self::LIB_LODASH_PHP],
            // Date
            ['now', self::LIB_LODASH_PHP],
            // Function
            ['flip', self::NOT_IMPLEMENTED],
            ['negate', self::NOT_IMPLEMENTED],
            ['overArgs', self::NOT_IMPLEMENTED],
            ['partial', self::NOT_IMPLEMENTED],
            ['partialRight', self::NOT_IMPLEMENTED],
            ['rearg', self::NOT_IMPLEMENTED],
            ['rest', self::NOT_IMPLEMENTED],
            ['spread', self::NOT_IMPLEMENTED],
            // Lang
            ['castArray', self::IN_PACKAGE],
            ['clone', self::NOT_IMPLEMENTED],
            ['cloneDeep', self::NOT_IMPLEMENTED],
            ['cloneDeepWith', self::NOT_IMPLEMENTED],
            ['conformsTo', self::NOT_IMPLEMENTED],
            ['eq', self::LIB_LODASH_PHP],
            ['gt', self::IN_PACKAGE],
            ['gte', self::IN_PACKAGE],
            ['isArguments', self::NOT_IMPLEMENTED],
            ['isArray', self::IN_PACKAGE],
            ['isArrayBuffer', self::NOT_IMPLEMENTED],
            ['isArrayLike', self::IN_PACKAGE],
            ['isArrayLikeObject', self::IN_PACKAGE],
            ['isBoolean', self::IN_PACKAGE],
            ['isBuffer', self::NOT_IMPLEMENTED],
            ['isDate', self::NOT_IMPLEMENTED],
            ['isElement', self::NOT_IMPLEMENTED],
            ['isEmpty', self::IN_PACKAGE],
            ['isEqual', self::LIB_LODASH_PHP],
            ['isEqualWith', self::NOT_IMPLEMENTED],
            ['isError', self::LIB_LODASH_PHP],
            ['isFinite', self::IN_PACKAGE],
            ['isFunction', self::NOT_IMPLEMENTED],
            ['isInteger', self::IN_PACKAGE],
            ['isLength', self::IN_PACKAGE],
            ['isMap', self::NOT_IMPLEMENTED],
            ['isMatch', self::IN_PACKAGE],
            ['isMatchWith', self::NOT_IMPLEMENTED],
            ['isNaN', self::IN_PACKAGE],
            ['isNative', self::NOT_IMPLEMENTED],
            ['isNil', self::NOT_IMPLEMENTED],
            ['isNull', self::IN_PACKAGE],
            ['isNumber', self::IN_PACKAGE],
            ['isObject', self::IN_PACKAGE],
            ['isObjectLike', self::NOT_IMPLEMENTED],
            ['isPlainObject', self::NOT_IMPLEMENTED],
            ['isRegExp', self::NOT_IMPLEMENTED],
            ['isSafeInteger', self::NOT_IMPLEMENTED],
            ['isSet', self::NOT_IMPLEMENTED],
            ['isString', self::IN_PACKAGE],
            ['isSymbol', self::NOT_IMPLEMENTED],
            ['isTypedArray', self::NOT_IMPLEMENTED],
            ['isUndefined', self::NOT_IMPLEMENTED],
            ['isWeakMap', self::NOT_IMPLEMENTED],
            ['isWeakSet', self::NOT_IMPLEMENTED],
            ['lt', self::IN_PACKAGE],
            ['lte', self::IN_PACKAGE],
            ['toArray', self::IN_PACKAGE],
            ['toFinite', self::IN_PACKAGE],
            ['toInteger', self::IN_PACKAGE],
            ['toLength', self::IN_PACKAGE],
            ['toNumber', self::IN_PACKAGE],
            ['toPlainObject', self::NOT_IMPLEMENTED],
            ['toSafeInteger', self::IN_PACKAGE],
            ['toString', self::IN_PACKAGE],
            // Math
            ['add', self::LIB_LODASH_PHP],
            ['ceil', self::IN_PACKAGE],
            ['divide', self::IN_PACKAGE],
            ['floor', self::IN_PACKAGE],
            ['max', self::LIB_LODASH_PHP],
            ['maxBy', self::LIB_LODASH_PHP],
            ['mean', self::IN_PACKAGE],
            ['meanBy', self::NOT_IMPLEMENTED],
            ['min', self::IN_PACKAGE],
            ['minBy', self::NOT_IMPLEMENTED],
            ['multiply', self::IN_PACKAGE],
            ['round', self::IN_PACKAGE],
            ['subtract', self::IN_PACKAGE],
            ['sum', self::IN_PACKAGE],
            ['sumBy', self::NOT_IMPLEMENTED],
            // Number
            ['clamp', self::LIB_LODASH_PHP],
            ['inRange', self::LIB_LODASH_PHP],
            ['random', self::LIB_LODASH_PHP], //untested
            // Object
            ['at', self::IN_PACKAGE],
            ['entries', self::IN_PACKAGE],
            ['entriesIn', self::IN_PACKAGE],
            ['findKey', self::NOT_IMPLEMENTED],
            ['findLastKey', self::NOT_IMPLEMENTED],
            ['functions', self::NOT_IMPLEMENTED],
            ['functionsIn', self::NOT_IMPLEMENTED],
            ['get', self::LIB_LODASH_PHP],
            ['has', self::IN_PACKAGE],
            ['hasIn', self::IN_PACKAGE],
            ['invert', self::IN_PACKAGE],
            ['invertBy', self::NOT_IMPLEMENTED],
            ['invoke', self::NOT_IMPLEMENTED],
            ['keys', self::IN_PACKAGE],
            ['keysIn', self::IN_PACKAGE],
            ['mapKeys', self::NOT_IMPLEMENTED],
            ['mapValues', self::NOT_IMPLEMENTED],
            ['omit', self::IN_PACKAGE],
            ['omitBy', self::NOT_IMPLEMENTED],
            ['pick', self::IN_PACKAGE],
            ['pickBy', self::NOT_IMPLEMENTED],
            ['result', self::IN_PACKAGE],
            ['toPairs', self::IN_PACKAGE],
            ['toPairsIn', self::IN_PACKAGE],
            ['transform', self::NOT_IMPLEMENTED],
            ['values', self::IN_PACKAGE],
            ['valuesIn', self::IN_PACKAGE],
            // String
            ['camelCase', self::LIB_LODASH_PHP],
            ['capitalize', self::LIB_LODASH_PHP],
            ['deburr', self::LIB_LODASH_PHP],
            ['endsWith', self::LIB_LODASH_PHP],
            ['escape', self::LIB_LODASH_PHP],
            ['escapeRegExp', self::LIB_LODASH_PHP],
            ['kebabCase', self::LIB_LODASH_PHP],
            ['lowerCase', self::LIB_LODASH_PHP],
            ['lowerFirst', self::LIB_LODASH_PHP],
            ['pad', self::LIB_LODASH_PHP],
            ['padEnd', self::LIB_LODASH_PHP],
            ['padStart', self::LIB_LODASH_PHP],
            ['parseInt', self::LIB_LODASH_PHP],
            ['repeat', self::LIB_LODASH_PHP],
            ['replace', self::LIB_LODASH_PHP],
            ['snakeCase', self::LIB_LODASH_PHP],
            ['split', self::LIB_LODASH_PHP],
            ['startCase', self::LIB_LODASH_PHP],
            ['startsWith', self::LIB_LODASH_PHP],
            ['toLower', self::LIB_LODASH_PHP],
            ['toUpper', self::LIB_LODASH_PHP],
            ['trim', self::LIB_LODASH_PHP],
            ['trimEnd', self::LIB_LODASH_PHP],
            ['trimStart', self::LIB_LODASH_PHP],
            ['truncate', self::LIB_LODASH_PHP],
            ['unescape', self::LIB_LODASH_PHP],
            ['upperCase', self::LIB_LODASH_PHP],
            ['upperFirst', self::LIB_LODASH_PHP],
            ['words', self::LIB_LODASH_PHP],
            // Util
            ['cond', self::NOT_IMPLEMENTED],
            ['conforms', self::NOT_IMPLEMENTED],
            ['constant', self::IN_PACKAGE],
            ['defaultTo', self::LIB_LODASH_PHP],
            ['flow', self::NOT_IMPLEMENTED],
            ['flowRight', self::NOT_IMPLEMENTED],
            ['identity', self::LIB_LODASH_PHP],
            ['iteratee', self::IN_PACKAGE],
            ['matches', self::IN_PACKAGE],
            ['matchesProperty', self::IN_PACKAGE],
            ['method', self::NOT_IMPLEMENTED],
            ['methodOf', self::NOT_IMPLEMENTED],
            ['nthArg', self::NOT_IMPLEMENTED],
            ['over', self::NOT_IMPLEMENTED],
            ['overEvery', self::NOT_IMPLEMENTED],
            ['overSome', self::NOT_IMPLEMENTED],
            ['property', self::LIB_LODASH_PHP],
            ['propertyOf', self::NOT_IMPLEMENTED],
            ['range', self::IN_PACKAGE],
            ['rangeRight', self::IN_PACKAGE],
            ['stubArray', self::IN_PACKAGE],
            ['stubFalse', self::IN_PACKAGE],
            ['stubObject', self::IN_PACKAGE],
            ['stubString', self::IN_PACKAGE],
            ['stubTrue', self::IN_PACKAGE],
            ['times', self::IN_PACKAGE],
            ['toPath', self::IN_PACKAGE],
            ['uniqueId', self::NOT_IMPLEMENTED],
        ];
        foreach ($lodashList as $lodashfunct) {
            if ($lodashfunct[1] == self::LIB_LODASH_PHP) {
                JsonLogic::add_operation('_'.$lodashfunct[0], '_Lodash::'.$lodashfunct[0]);
            }

            if ($lodashfunct[1] == self::IN_PACKAGE) {
                JsonLogic::add_operation('_'.$lodashfunct[0], [___::class, $lodashfunct[0]]);
            }
        }
    }
}
