name: PHPUnit Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      matrix:
        fail-fast: false
        php-versions: ['8.0']
        experimental: [false]
        include:
          - php-versions: '8.1'
            experimental: true

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.12.0
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2.1.5
        with:
          path: vendor
          key: php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php-${{ matrix.php-versions }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Configure matchers
        uses: mheap/phpunit-matcher-action@v1

      - name: Run Tests
        run: php vendor/bin/phpunit --log-junit=.build/junit.xml --coverage-clover .build/clover.xml --teamcity
      - uses: EnricoMi/publish-unit-test-result-action@v1.15
        if: github.actor != 'dependabot[bot]' && always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: .build/junit.xml

      - name: Record Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php vendor/bin/php-coveralls --coverage_clover=.build/clover.xml --json_path=.build/coveralls-upload.json
